objects/Account.object
<CustomObject>
    <fields>
        <fullName>RUT__c</fullName>
        <description>RUT para Empresas y Personas (RUT for Accounts and Person Accounts)</description>
        <externalId>true</externalId>
        <label>RUT</label>
        <length>13</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/BICE_HouseHold__c.object
<CustomObject>
    <label>BICE HouseHold</label>
    <nameField>
        <label>HouseHold Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BICE HouseHolds</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/BICE_HouseHoldTest.cls
@isTest
private class BICE_HouseHoldTest{
    static testMethod void householdcreation() {
        Account acc = new Account();
        acc.FirstName = 'Sam';
        acc.LastName = 'Nectia';
        acc.RUT__c = '61001000-8';        
        insert acc;        
        BICE_HouseHold__c bh = new BICE_HouseHold__c();
        bh.Name = (acc.FirstName+acc.LastName+acc.RUT__c).toLowerCase();        
        insert bh;
    }    
}