objects/Account.object
<CustomObject>
    <fields>
        <fullName>HouseHoldName__c</fullName>
        <formula>LOWER(FirstName+LastName+RUT__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>HouseHoldName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HouseHold__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>HouseHold</label>
        <referenceTo>BICE_HouseHold__c</referenceTo>
        <relationshipLabel>Cuentas</relationshipLabel>
        <relationshipName>Cuentas</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/BICE_HouseHold__c.object
<CustomObject>
    <label>BICE HouseHold</label>
    <nameField>
        <label>HouseHold Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BICE HouseHolds</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/UpdateAccountHouseHold.cls
global class UpdateAccountHouseHold implements Database.Batchable<sObject> {
 
 Set<String> HHName = new Set<String>();

    global UpdateAccountHouseHold( Set<String> HHn ) {
        HHName = HHn;
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        return DataBase.getQueryLocator([select id,HouseHoldName__c from Account where HouseHoldName__c IN :  HHName]);
    }

    global void execute(Database.BatchableContext BC,List<Account> scopeAcc) {
    
           for(BICE_HouseHold__c bh: [SELECT Id,Name FROM BICE_HouseHold__c]){
                for (Integer i=0;i<scopeAcc.size();i++){
                    if(scopeAcc[i].HouseHoldName__c == bh.Name)
                        scopeAcc[i].HouseHold__c = bh.id;
                }
            
           }
           update scopeAcc;
    }
    

    global void finish(Database.BatchableContext BC) {
   
    }
}